server:
  port: 6002
spring:
  application:
    name: mumu-product
  redis:
    host: mumu-redis
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  thymeleaf:
    prefix: classpath:/templates/
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/



