server:
  port: 6002
spring:
  application:
    name: mumu-product
  redis:
    host: 47.115.51.108
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

  thymeleaf:
    prefix: classpath:/templates/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/


zookeeper:
  address: 47.115.51.108:2181
  retryCount: 5
  elapsedTimeMs: 500
  sessionTimeoutMs: 30000
  connectionTimeoutMs: 10000


