server:
  port: 6001
spring:
  application:
    name: mumu-gateway
  cloud:
    gateway:
      routes:
        #路由的ID
        - id: mumu-product
        #lb表示从注册中心获取服务
          uri: lb://mumu-product
          predicates:
          #匹配规则
            - Path=/b/product/**

      default-filters:
        - name: RequestRateLimiter
          args:
            #限流策略对于的bean对象
            key-resolver: '#{@pathKeyResolver}'
            #令牌桶每秒的填充速度
            redis-rate-limiter.replenishRate: 1
            #令牌桶容量
            redis-rate-limiter.burstCapacity: 3


  redis:
    host: mumu-redis
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/



